version: "3"
services:
  five-stars:
    build: .
    env_file: ./.env
    image: desertmark/five-stars
    ports:
      - "4000:4000"

  cosmos:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    container_name: cosmosdb
    ports:
      - "4000:4000"
      - "8081:8081"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=192.168.1.135
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 3g
